# Generated by Django 6.0.4 on 2026-04-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_participantlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participantlink',
            new_name='imports_par_partici_4715eb_idx',
            old_name='imports_par_partici_5f1afe_idx',
        ),
    ]
